name: ci

on:
  push:
    branches: [test, main]

  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CI:
    name: Run CI
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name : Check style code
        run : |
          sudo apt-get install -y cppcheck
          cppcheck --enable=warning,style,performance,portability ./func.c
          cppcheck --enable=warning,style,performance,portability ./main.c
          cppcheck --enable=warning,style,performance,portability ./test_iz1.cpp
          
      - name : Building
        run : |
          mkdir build
          cd build
          sudo apt-get install -y libgtest-dev
          cmake ..
          make
          cd ..
          
      - name: Coverage test
        run: |
          sudo apt-get install lcov
          ./build/test_iz1
          mkdir coverage && cd coverage
          gcov ../build/CMakeFiles/func.dir/func.c.gcno
          cp -r ../build/CMakeFiles/func.dir/ .
          cd ..
          lcov --capture --directory coverage/ --output-file func.info
          genhtml func.info --output-directory coverage-report/
          
      - name: Archive coverage test results
        uses: actions/upload-artifact@v2
        with:
          name: Coverage test
          path: coverage-report/

      - name: Valgrind test
        run: |
          sudo apt-get install -y valgrind
          mkdir valgrid-output
          valgrind --leak-check=full --tool=memcheck --show-leak-kinds=all --log-file=valgrid-output/report -q ./build/test_iz1
          
      - name: Archive valgrind test results
        uses: actions/upload-artifact@v2
        with:
          name: Valgrind test
          path: valgrid-output/